"""GENERATED by gen_name_banks.py -- FF1 PSP (US) menu NAME text banks.

Vanilla payload bytes of the weapon/armor/item name TEXT banks (from the
ISO's FM_EXTERN12US.PC; identical bytes are what the game loads into RAM),
plus the MENU-font glyph map and the game-id -> entry-index permutation.
The client uses these to author AP item names into shop name entries via
boot_patch.DataPatch (payload == RAM search signature). Do not edit.
"""
import base64

TERM = 0x06          # menu-string terminator glyph

# menu glyph byte -> char (solved; distinct from font_map.FONT!).
# digit strip is "1234567890" order: 0x38..0x40 = '1'..'9', 0x41 = '0'.
# VERIFIED LIVE 2026-07-02 ("880 Gil": earlier 0x38='0' map gave "991"; a naive
# -1 shift gave "88q"; this order renders correctly).
MENU_FONT = {
    0x00: ' ',
    0x01: 'e',
    0x02: 'a',
    0x03: 't',
    0x04: 's',
    0x05: 'r',
    0x07: 'o',
    0x08: 'l',
    0x09: 'i',
    0x0a: 'n',
    0x0b: 'd',
    0x0c: 'h',
    0x0d: '.',
    0x0e: 'f',
    0x0f: 'm',
    0x10: 'u',
    0x11: 'g',
    0x12: 'c',
    0x13: 'w',
    0x14: 'A',
    0x15: 'y',
    0x16: 'p',
    0x17: 'b',
    0x18: 'k',
    0x19: 'S',
    0x1a: 'C',
    0x1b: 'v',
    0x1c: 'P',
    0x1d: 'R',
    0x1e: 'H',
    0x1f: "'",
    0x20: 'D',
    0x21: 'M',
    0x22: 'B',
    0x23: 'G',
    0x24: 'x',
    0x25: 'T',
    0x26: 'F',
    0x27: 'L',
    0x28: 'z',
    0x29: 'E',
    0x2a: 'N',
    0x2b: 'W',
    0x2c: 'K',
    0x2d: 'I',
    0x2e: 'j',
    0x30: 'O',
    0x31: '-',
    0x33: 'V',
    0x35: 'J',
    0x38: '1',
    0x39: '2',
    0x3a: '3',
    0x3b: '4',
    0x3c: '5',
    0x3d: '6',
    0x3e: '7',
    0x3f: '8',
    0x40: '9',
    0x41: '0',
    0x42: 'X',
    0x43: 'U',
    0x44: 'Z',
    # Read straight off the bundle's own .FIF ascii->glyph table 2026-08-08 (see
    # the PAGE block below) and confirmed against the .GIM strip: the menu font
    # is a COMPLETE printable-ASCII face. The constraint solver could not learn
    # these because no vanilla item name uses them, so 'Q'/'Y'/'q' used to fall
    # back to the wrong case and every symbol was dropped.
    0x2f: ',',
    0x37: 'q',
    0x45: 'Q',
    0x47: '!',
    0x48: '"',
    0x49: '#',
    0x4a: '$',
    0x4b: '%',
    0x4c: '&',
    0x4d: '(',
    0x4e: ')',
    0x4f: '*',
    0x50: '+',
    0x51: '/',
    0x59: ':',
    0x5a: ';',
    0x5b: '<',
    0x5c: '=',
    0x5d: '>',
    0x5e: '?',
    0x5f: '@',
    0x60: 'Y',
    0x61: '[',
    0x62: '\\',
    0x63: ']',
    0x64: '^',
    0x65: '_',
    0x66: '`',
    0x67: '{',
    0x68: '|',
    0x69: '}',
    0x6a: '~',
}
MENU_ENC = {c: g for g, c in MENU_FONT.items()}


def menu_encode_fit(s, budget):
    """Menu-font glyphs for s, truncated to `budget` and space-padded to
    exactly `budget` bytes. Unknown caps fall back to lowercase; anything
    else unencodable is dropped. Only solved glyph bytes are emitted."""
    out = bytearray()
    for c in s:
        if len(out) >= budget:
            break
        if c in MENU_ENC:
            out.append(MENU_ENC[c])
        elif c.isupper() and c.lower() in MENU_ENC:
            out.append(MENU_ENC[c.lower()])
        elif c in ' _':
            out.append(MENU_ENC[' '])
    out += bytes([MENU_ENC[' ']]) * (budget - len(out))
    return bytes(out)


# --- the glyph PAGES, and why the bake collapses them to one -------------
# RE'd on disc 2026-08-08 from each bundle's own .FIF ascii->glyph table (u16
# magic, u16 glyph_count, then a 276-byte char->glyph u16 table) with the .GIM
# strip rendered out to confirm every id. FM_EXTERN12US (the 12 px menu face)
# and FM_EXTERN18US (the 18 px box face) carry the SAME 107 glyphs with exactly
# ONE block permuted:
#   MENU page (12US): 0x38..0x41 = wide digits 1234567890, 0x42..0x45 = X U Z Q
#   BOX  page (18US): 0x38..0x3b = X U Z Q,  0x3c..0x45 = wide digits 1234567890
# Every letter, the proportional digits (0x32/0x34/0x36, 0x52..0x58), 'Y' 0x60
# and all punctuation share an id on both pages, so only these 14 move.
#
# Square stores each bundle's NAME banks in its own page (ITEM/WEAPON/ARMOR/
# MAGIC_NAME differ between the bundles by exactly the one swapped byte;
# VALUE.MSG's digit strip reads "1234567890" on both; the *_EXP desc banks are
# identical copies). But the RUNTIME does not honour that pairing: it serves the
# 12US banks and hands them to BOTH faces. So the 18 px chest reward box draws
# menu-page bytes through box-page ids and every X/U/Z/Q comes out a digit --
# "DragoniteZ3OW" -> "Dragonite9OW" (2026-08-08), and vanilla "Ultima Weapon"
# out of a Cornelia chest -> "8ltima Weapon" (2026-08-10), while the item menu
# rendered the very same bytes correctly. The same mismatch is what the
# 2026-07-23 key-menu probe saw (0x38 drew 'X', 0x3c.. drew "1234").
#
# extern_bake therefore PERMUTES THE 18US FONT ITSELF onto the menu page (14
# glyph-metric records + its char table; the .GIM pixels never move) and
# re-encodes that bundle's own banks to match. After a bake there is ONE page in
# the whole game, every UI agrees, and nothing here needs a per-surface encoder.
# KEY_MENU_ENC is consequently just MENU_ENC again.
PAGE_SWAP = {0x38: 0x3C, 0x39: 0x3D, 0x3A: 0x3E, 0x3B: 0x3F, 0x3C: 0x40,
             0x3D: 0x41, 0x3E: 0x42, 0x3F: 0x43, 0x40: 0x44, 0x41: 0x45,
             0x42: 0x38, 0x43: 0x39, 0x44: 0x3A, 0x45: 0x3B}
PAGE_UNSWAP = {v: k for k, v in PAGE_SWAP.items()}
_TO_BOX_TBL = bytes(PAGE_SWAP.get(b, b) for b in range(256))
_TO_MENU_TBL = bytes(PAGE_UNSWAP.get(b, b) for b in range(256))

BOX_FONT = {PAGE_SWAP.get(g, g): c for g, c in MENU_FONT.items()}
BOX_ENC = {c: g for g, c in BOX_FONT.items()}

# Historical alias. The key menu draws with the 18 px face, so before the font
# was unified this had to be the box page; a baked ISO is menu page everywhere.
KEY_MENU_ENC = MENU_ENC


def to_box_page(entry):
    """A menu-page glyph ENTRY re-encoded onto the box page.

    ENTRY PAYLOADS ONLY. A TEXT bank's u32 offset table can hold any byte, so
    translating a whole bank blob would corrupt it; callers must slice entries
    first. Multi-byte controls are safe: the icon / line-break pairs are
    0xc2 0x88 / 0xc2 0x8d and the terminator is 0x06 -- none land in
    0x38..0x45. The swap is NOT an involution (it rotates a 14-id block), so
    never apply it twice; use from_box_page to go back."""
    return bytes(entry).translate(_TO_BOX_TBL)


def from_box_page(entry):
    """Inverse of to_box_page: a box-page ENTRY re-encoded onto the menu page.
    Same entry-payloads-only rule."""
    return bytes(entry).translate(_TO_MENU_TBL)


def key_menu_encode(s, budget):
    """Glyphs for s in the KEY ITEMS menu font (letters = MENU_ENC, digits on
    the key-menu page), truncated to `budget` and space-padded to exactly
    `budget` bytes. The menu draws off[i+1]-off[i] bytes and IGNORES the TERM,
    so the slot must be fully space-filled or stale glyphs show through."""
    out = bytearray()
    for c in s:
        if len(out) >= budget:
            break
        if c in KEY_MENU_ENC:
            out.append(KEY_MENU_ENC[c])
        elif c.isupper() and c.lower() in KEY_MENU_ENC:
            out.append(KEY_MENU_ENC[c.lower()])
        elif c in " _":
            out.append(KEY_MENU_ENC[" "])
    out += bytes([KEY_MENU_ENC[" "]]) * (budget - len(out))
    return bytes(out)


def menu_encode(s, max_glyphs=None):
    """Menu-font glyphs for s, NO padding. Unknown caps fall back to
    lowercase; anything else unencodable is dropped. Truncates at
    max_glyphs when given."""
    out = bytearray()
    for c in s:
        if max_glyphs is not None and len(out) >= max_glyphs:
            break
        if c in MENU_ENC:
            out.append(MENU_ENC[c])
        elif c.isupper() and c.lower() in MENU_ENC:
            out.append(MENU_ENC[c.lower()])
        elif c in ' _':
            out.append(MENU_ENC[' '])
    return bytes(out)


# cat -> dict(icon_len, payload (b64), entry_offsets, gameid_to_entry)
# entry i occupies payload[entry_offsets[i]:entry_offsets[i+1]] (last ->
# end); layout: icon_len icon bytes + name glyphs + TERM.
BANKS = {
    'weapons': {
        'icon_len': 1,
        'payload': base64.b64decode(
            'eywKCQ4BBn8ZAwIODgZ/HgECCAkKEQAZAwIODgZ7IAIREQEFBn4eAg8PAQUGeR0CFgkBBQZ6'
            'GRIJDwkDAgUGeyEVAwwFCQgALAoJDgEGfCoQChIMAhgQBn8cBxMBBQAZAwIODgZ+IRUDDAUJ'
            'CAAeAg8PAQUGfyECEQEfBAAZAwIODgZ5GQIXAQUGfxoFBwQJAQUGeiYCCBIMCQcKBnkiBQcC'
            'CwQTBwULBn8rCSgCBQsfBAAZAwIODgZ8LQUHCgAqEAoSDAIYEAZ9IgIDAwgBABQkAQZ5HRAK'
            'AQAiCAILAQZ5KwEFARcQBAMBBQZ+JQwHBR8EAB4CDw8BBQZ5KxUFDxgJCAgBBQZ5GgcFAggA'
            'GRMHBQsGeScHChEEEwcFCwZ5IwUBAgMAGRMHBQsGfSMFAQIDABQkAQZ5HQIoAQUGexoCAwAa'
            'CAITBAZ5IRUDDAUJCAAZEwcFCwZ5MwcFFgIIABkTBwULBn0hFQMMBQkIABQkAQZ5JggCDwEA'
            'GRMHBQsGfScJEQwDABQkAQZ5LRIBACIFAgoLBnkgAQ4BCgsBBQZ5GRAKACIIAgsBBnoZAgQQ'
            'GAEfBAAiCAILAQZ5KSQSAggJFxAFBnohAgQCDxAKAQZ5QwgDCQ8CACsBAhYHCgZ5HQIRCgIF'
            'BxgGeiEQBQIEAg8BBnknCREMAxcFCQoRAQUGfx0QCgEAGQMCDg4GfzUQCxEPAQoDABkDAg4O'
            'BnkgAgUYABoIAhUPBwUBBnkgEAEIAB0CFgkBBQZ5IgUCGwEMAQIFAwZ5IAECAwwXBQkKEQEF'
            'BnkpCgwCChIBBQZ9IwkRAgoDAiQBBn0zCRgJChEAFCQBBn0dEAoBABQkAQZ9MBEFARgJCAgB'
            'BQZ6LAkYEAkSDAkPBwouCQZ6FAQQBQIGeiwHAwEDBBAGfisCBQAeAg8PAQUGexQEBAIEBAkK'
            'ACACEREBBQZ7MAUJEgwCCBIQDwZ7IQIRAQAhAgQMAQUGeyMIAgsJEAQGfxkCEQEfBAAZAwIO'
            'DgZ5IgIFFwIFCQIKHwQAGRMHBQsGeycQBAMAIAIREQEFBn8jBwgLAQoAGQMCDg4G'),
        'entry_offsets': [0, 7, 14, 29, 37, 45, 53, 63, 78, 88, 101, 117, 131, 138, 147, 157, 169, 185, 200, 212, 224, 236, 251, 263, 276, 287, 300, 311, 318, 329, 344, 358, 371, 384, 395, 406, 416, 427, 443, 454, 464, 479, 489, 499, 513, 525, 541, 556, 569, 581, 595, 605, 616, 628, 638, 650, 665, 672, 681, 693, 710, 722, 735, 744, 758, 777, 790],
        'gameid_to_entry': {2: 0, 3: 1, 30: 2, 10: 3, 5: 4, 4: 5, 8: 6, 16: 7, 1: 8, 28: 9, 18: 10, 31: 11, 12: 12, 11: 13, 15: 14, 6: 15, 33: 16, 9: 17, 7: 18, 27: 19, 26: 20, 36: 21, 22: 22, 25: 23, 13: 24, 23: 25, 14: 26, 37: 27, 35: 28, 17: 29, 34: 30, 19: 31, 20: 32, 29: 33, 21: 34, 32: 35, 24: 36, 38: 37, 39: 38, 40: 39, 41: 40, 42: 41, 43: 42, 44: 43, 45: 44, 46: 45, 47: 46, 48: 47, 49: 48, 50: 49, 51: 50, 52: 51, 53: 52, 54: 53, 55: 54, 56: 55, 57: 56, 58: 57, 59: 58, 60: 59, 61: 60, 62: 61, 63: 62, 64: 63, 65: 64, 66: 65, 67: 66},
    },
    'armor': {
        'icon_len': 2,
        'payload': base64.b64decode(
            'woAaCAcDDAEEBsKBJwECAwwBBQAUBQ8HBQbCghoHFhYBBQAUBQ8IAQMGwoEaDAIJCgAhAgkI'
            'BsKCGQkIGwEFABQFDwgBAwbCgSEVAwwFCQgAIQIJCAbCgS0FBwoAFAUPBwUGwoArDAkDAQAd'
            'BxcBBsKAIggCEhgAHQcXAQbCgh0QFxUAFAUPCAEDBsKBLAoJEQwDHwQAFAUPBwUGwoEmCAIP'
            'AQAhAgkIBsKBLRIBABQFDwcFBsKCIAkCDwcKCwAUBQ8IAQMGwoEgCQIPBwoLABQFDwcFBsKB'
            'IAUCEQcKACECCQgGwoMnAQIDDAEFABkMCQEICwbCgyIQEhgIAQUGwoMtBQcKABkMCQEICwbC'
            'gxwFBwMBEgMAGggHAhgGwoMhFQMMBQkIABkMCQEICwbCgyYIAg8BABkMCQEICwbCgy0SAQAZ'
            'DAkBCAsGwoMgCQIPBwoLABkMCQEICwbCgxQBEQkEABkMCQEICwbChScBAgMMAQUAIwgHGwEE'
            'BsKFIgUHCigBACMIBxsBBAbChRkDAQEIACMIBxsBBAbChSEVAwwFCQgAIwgHGwEEBsKFIwIQ'
            'CgMIAQMEBsKFIwkCCgMfBAAjCAcbAQQGwoUgCQIPBwoLACMIBxsBBAbChRwFBwMBEgMAHQkK'
            'EQbChCcBAgMMAQUAGgIWBsKEHQkXFwcKBsKEHgEIDwbChCMFAQIDAB4BCA8GwoQhFQMMBQkI'
            'AB4BCA8GwoQeAQIICQoRAB4BCA8GwoQgCQIPBwoLAB4BCA8GwoEaBRUEAwIIACECCQgGwoIl'
            'DAkBDh8EABQFDwgBAwbCgCIIAhIYACMCBRcGwoAsAQoWBxEJBsKAHAcTAQUAGQIEDAbCgB0B'
            'CwA1AhIYAQMGwoAZAhEBHwQAGRAFFggJEgEGwoAnCREMAwAdBxcBBsKAIwIJAgAjAQIFBsKA'
            'IgIFCx8EACUQCgkSBsKBIwEKLgkAFAUPBwUGwoMjAQouCQAZDAkBCAsGwoMaBRUEAwIIABkM'
            'CQEICwbCgx4BBQcfBAAZDAkBCAsGwoNEARYMFQUAGgIWAQbCgykIGwEKABoIBwIYBsKFGgUV'
            'BAMCCAAjCAcbAQQGwoUlDAkBDh8EACMIBxsBBAbChRoFFQQDAggAHQkKEQbChRQKEQEIHwQA'
            'HQkKEQbChSMBCi4JACMIBxsBBAbChCMBCi4JAB4BCA8GwoQaBRUEAwIIAB4BCA8GwoQiCAIS'
            'GAAaBxMIBsKEJRMJBAMAHgECCxcCCgsGwoQlCREBBQAhAgQYBsKEJgECAwwBBQELABoCFgbC'
            'hB0BCwAaAhYGwoQrCSgCBQsfBAAeAgMGwoQZAhEBHwQAIQkDBQEGwoMhAgQDAQUAGQwJAQgL'
            'BsKEGQwCCwcTACECBBgGwoEhAiQJDwkICAkCCgbCgBkQBRsJGwIIADMBBAMGwoAnBwULCBUA'
            'HQcXAQQG'),
        'entry_offsets': [0, 10, 26, 42, 55, 71, 86, 99, 112, 125, 139, 156, 169, 181, 198, 214, 228, 245, 255, 269, 285, 302, 317, 330, 347, 362, 379, 395, 410, 427, 439, 456, 473, 488, 502, 511, 518, 531, 546, 561, 576, 591, 608, 621, 631, 644, 657, 675, 688, 700, 715, 729, 744, 761, 777, 791, 805, 822, 839, 854, 869, 884, 897, 912, 925, 942, 955, 971, 981, 996, 1011, 1027, 1041, 1055, 1071],
        'gameid_to_entry': {1: 0, 2: 1, 11: 2, 3: 3, 12: 4, 6: 5, 4: 6, 15: 7, 16: 8, 13: 9, 5: 10, 7: 11, 8: 12, 14: 13, 9: 14, 10: 15, 31: 16, 38: 17, 32: 18, 39: 19, 33: 20, 34: 21, 35: 22, 36: 23, 37: 24, 63: 25, 64: 26, 65: 27, 66: 28, 67: 29, 68: 30, 69: 31, 70: 32, 46: 33, 52: 34, 47: 35, 48: 36, 49: 37, 51: 38, 50: 39, 17: 40, 18: 41, 19: 42, 20: 43, 21: 44, 22: 45, 23: 46, 24: 47, 25: 48, 26: 49, 27: 50, 40: 51, 41: 52, 42: 53, 43: 54, 44: 55, 71: 56, 72: 57, 73: 58, 74: 59, 75: 60, 53: 61, 54: 62, 55: 63, 56: 64, 57: 65, 58: 66, 59: 67, 60: 68, 61: 69, 45: 70, 62: 71, 28: 72, 29: 73, 30: 74},
    },
    'items': {
        'icon_len': 2,
        'payload': base64.b64decode(
            'wogcBwMJBwoGwokUCgMJCwcDAQbCiSMHCAsAKgEBCwgBBsKKGQgBARYJChEAIgIRBsKKJQEK'
            'AwbCihoHAwMCEQEGwogeCTEcBwMJBwoGwohCMRwHAwkHCgbCiCkDDAEFBsKIJRAFFwcAKQMM'
            'AQUGwoggBRUAKQMMAQUGwogpCAkkCQUGwoghARECCAkkCQUGwokcDAcBCgkkACAHEwoGwokd'
            'AQ8BCxUGwokpFQEAIAUHFgQGwokpEgwHACMFAgQEBsKJKQ8BBREBChIVACkkCQMGwokZFgkL'
            'AQUfBAAZCQgYBsKJKwwJAwEAJgIKEQbCiR0BCwAmAgoRBsKJIggQAQAmAgoRBsKJJwkRDAMA'
            'GhAFAwIJCgbCiR0BCwAaEAUDAgkKBsKJKwwJAwEAGhAFAwIJCgbCiSIIEAEAGhAFAwIJCgbC'
            'iScQCgIFABoQBQMCCQoGwokeAQUPAQQfABkMBwEEBsKJMwIPFgkFAQAmAgoRBsKJGgcSGAID'
            'BQkSAQAaCAITBsKJHAcTAQUAHAgQBAbCiRkDAg8JCgIAHAgQBAbCiSEJCgsAHAgQBAbCiRkW'
            'AQELABwIEAQGwoknEBIYABwIEAQGwokjBwgLAQoAFBYWCAEGwokZCQgbAQUAFBYWCAEGwokZ'
            'Bw8CACAFBxYGwogZAwUBChEDDAAlBwoJEgbCiCMJAgoDHwQAJQcKCRIGwogmAgEFCQEAJQcK'
            'CRIGwogcBQcDARIDACAFCQoYBsKIGRYBAQsAIAUJChgG'),
        'entry_offsets': [0, 9, 20, 34, 49, 56, 66, 78, 89, 97, 111, 123, 132, 144, 159, 168, 180, 193, 210, 226, 239, 250, 262, 278, 292, 308, 323, 339, 355, 370, 388, 401, 416, 428, 441, 453, 468, 483, 495, 512, 528, 543, 559],
        'gameid_to_entry': {1: 0, 11: 1, 12: 2, 16: 3, 17: 4, 18: 5, 2: 6, 3: 7, 4: 8, 5: 9, 6: 10, 7: 11, 8: 12, 9: 13, 10: 14, 13: 15, 14: 16, 15: 17, 19: 18, 20: 19, 21: 20, 22: 21, 23: 22, 24: 23, 25: 24, 26: 25, 27: 26, 28: 27, 29: 28, 30: 29, 39: 30, 40: 31, 41: 32, 42: 33, 43: 34, 36: 35, 37: 36, 38: 37, 33: 38, 31: 39, 32: 40, 34: 41, 35: 42},
    },
}

# Name banks that are STANDALONE TEXT containers: 0x10 header, then a u32
# offset table (values relative to the bank/TEXT start), then the packed
# entries -- exactly the DESC_BANKS layout. Verified LIVE 2026-07-07 by
# searching resident RAM for the computed table bytes: weapons and armor
# match on both resident copies with the entries immediately following.
# The ITEMS name bank does NOT qualify: with spell_tomes on, extern_bake
# GROWS it on disc (43 -> 107 entries), so its offset table differs per seed
# (the live probe saw the grown table's far-forward offsets) -- a table-
# inclusive signature would miss, exactly the shopdesc:items bug of
# 2026-07-03. Its entries keep their fixed vanilla budgets (entries-only
# signature still matches the grown bank's front).
RELAYOUT_KEYS = ('weapons', 'armor')

# Shop-list column width guard: longest authored shop name, in glyphs.
MAX_NAME_GLYPHS = 24


def bank_container(key):
    """(vanilla_bytes, entry_base) of the full relocatable region of a
    standalone name bank: u32 offset table + packed entries. entry_base =
    bank-relative offset of the first entry (0x10 header + table)."""
    bank = BANKS[key]
    offs, payload = bank['entry_offsets'], bank['payload']
    # entry_offsets are PAYLOAD-relative as captured from memory, but the
    # on-disc table stores BANK-relative offsets (0x10 header + table
    # precede the payload). This `base + o` rebase is the source of every
    # +-0x10 adjustment in the bank modules.
    base = 0x10 + len(offs) * 4
    table = b''.join((base + o).to_bytes(4, 'little') for o in offs)
    return table + payload, base


def relayout_name_bank(key, authored, prefix_keep=None):
    """Re-lay a standalone name bank so authored entries may exceed their
    vanilla byte budgets (the whole point: long multiworld item names).

    authored: {entry_index: label string}. Each authored entry keeps its
    vanilla icon bytes, gets the label's glyphs (capped at MAX_NAME_GLYPHS)
    + TERM; every other entry is byte-identical, just re-addressed via the
    rewritten offset table. Total container length is constant (tail
    zero-padded). If the bank overflows, the longest authored name is
    word-boundary trimmed until everything fits.

    `prefix_keep` ({entry_index: glyphs}) marks a fixed PREFIX that entry
    carries (hint rows spend 6 glyphs on "HINT: ", see hints.NAME_PREFIX). This
    bank is TIGHT -- 804 bytes over 67 entries, so any authored seed equalizes
    its names at ~10-14 glyphs -- and a prefixed name would otherwise lose twice
    over: counted as the longest entry because of the prefix, then word-trimmed
    at the prefix's own space until nothing but the prefix was left. A kept
    prefix is discounted when picking the next victim, is never trimmed away,
    and turns the word-boundary cut into a character cut once only the prefix
    would survive it.

    Returns (vanilla_full, new_full) for a same-length DataPatch, or None
    when it cannot fit / nothing changes (caller falls back to the fixed-
    budget in-place path)."""
    if key not in RELAYOUT_KEYS:
        raise ValueError(f"name bank {key!r} cannot be re-laid out")
    bank = BANKS[key]
    offs, payload, icon = (bank['entry_offsets'], bank['payload'],
                           bank['icon_len'])
    keeps = prefix_keep or {}
    vanilla_full, base = bank_container(key)
    ends = list(offs[1:]) + [len(payload)]
    ents = [bytearray(payload[s:e]) for s, e in zip(offs, ends)]
    capacity = len(payload)
    for ei, label in authored.items():
        body = menu_encode(label, MAX_NAME_GLYPHS)
        ents[ei] = bytearray(bytes(ents[ei][:icon]) + body + bytes([TERM]))
    sp = MENU_ENC[' ']
    while sum(map(len, ents)) > capacity:
        # Only entries that still have something to give up: an entry trimmed
        # down to its kept prefix is out of the running, but the others carry
        # on (returning None here would drop the whole patch).
        cands = [k for k in authored
                 if len(ents[k]) - icon - 1 > max(1, keeps.get(k, 0))]
        if not cands:
            return None                      # unfittable; caller falls back
        ei = max(cands, key=lambda k: len(ents[k]) - keeps.get(k, 0))
        keep = keeps.get(ei, 0)
        body = bytes(ents[ei][icon:-1])
        cut = body[:-1].rfind(sp)
        body = body[:cut] if cut > keep else body[:-1]
        ents[ei] = bytearray(bytes(ents[ei][:icon]) + body + bytes([TERM]))
    new_offs, p = [], base
    for e in ents:
        new_offs.append(p)
        p += len(e)
    table = b''.join(o.to_bytes(4, 'little') for o in new_offs)
    body = b''.join(bytes(e) for e in ents)
    new_full = table + body + b'\x00' * (capacity - len(body))
    assert len(new_full) == len(vanilla_full)
    return None if new_full == vanilla_full else (vanilla_full, new_full)


# Item DESCRIPTION text banks (shop bottom-bar text). Same entry order as
# the matching name bank (reuse BANKS[cat]['gameid_to_entry']); NO icon
# prefix. payload = OFFSET TABLE + entries (everything after the 0x10-byte
# TEXT header), so a DataPatch can re-lay the whole bank out: rewrite the
# u32 offsets (relative to the BANK START, i.e. first value == 0x10 +
# count*4) and repack the entries, keeping len(payload) constant.
# 'first' = vanilla start of the entry region, relative to bank start.
DESC_BANKS = {
    'weapons': {
        'count': 67,
        'first': 284,
        'payload': base64.b64decode(
            'HAEAACsBAAA7AQAAXgEAAG0BAACHAQAApQEAAMIBAADgAQAA8QEAABECAAAwAgAAUwIAAHMC'
            'AACVAgAAuQIAAOACAAAGAwAAHQMAADUDAABdAwAAgwMAAKkDAADMAwAA9AMAABEEAAAzBAAA'
            'UAQAAHYEAACYBAAAtgQAANMEAADwBAAAEAUAADMFAABWBQAAegUAAJwFAAC6BQAA4AUAAAEG'
            'AAAkBgAASwYAAHEGAACUBgAAugYAAN4GAAAFBwAAIgcAAEgHAABsBwAAkgcAALcHAADXBwAA'
            '+wcAABwIAABBCAAAZQgAAIsIAACnCAAAywgAAPEIAAAXCQAAPQkAAGAJAACCCQAAoQkAABQA'
            'BA8CCAgAGAoJDgENBhQAEwcHCwEKAAQDAg4ODQYUAAQDAg4OAAMMAgMAEgIEAwQAHgECCAAT'
            'DAEKABAEAQsNBhQACAIFEQEAGAoJDgENBhQADAIPDwEFAA8CCwEADgcFABcCAwMIAQ0GFAAE'
            'EwcFCwATCQMMAAIABAgBCgsBBQAXCAILAQ0GFAAEEwcFCwATCQMMAAIAEhAFGwELABcIAgsB'
            'DQYUABgKCQ4BABMFBxARDAMADgUHDwAPFQMMBQkIDQYrBwcLAQoAChAKEgwCGBANBhQABAMC'
            'Dg4AEwkDDAARBwcLAAIDAwISGAAWBxMBBQ0GFAAMAg8PAQUAEwUHEBEMAwAOBQcPAA8VAwwF'
            'CQgNBhQABAMCDg4AAwwCAwASAgQDBAAmCQUCABMMAQoAEAQBCw0GFAAIBwoRAAQTBwULAA8C'
            'CwEADgcFABYJAQUSCQoRDQYUAAQDAg4OAAMHFhYBCwATCQMMAAIKAAkFBwoABQkKEQ0GFAAE'
            'EwcFCwADDAIDABMJCwEKBAADBxMCBQsACQMEAAMJFg0GGRMHBQsAEwkDDAACABMJCwEvAAsH'
            'EBcIATEBCxEBCwAXCAILAQ0GFAAEAwIODgADDAIDABICBAMEABoHCg4QBAEAEwwBCgAQBAEL'
            'DQYqEAoSDAIYEAAPAgsBAAcOAAkFBwoNBhQKAAIkAQAPAgsBAA4HBQAXAgMDCAENBhQABBMH'
            'BQsAAQ4OARIDCRsBAAIRAgkKBAMABBYBCAgSAgQDAQUEDQYUAAQTBwULAAEODgESAwkbAQAC'
            'EQIJCgQDABMBBQEXAQIEAwQNBh4CDw8BBQADDAIDABICBAMEACUMEAoLAgUCABMMAQoAEAQB'
            'Cw0GFAAEEwcFCwABDg4BEgMJGwEAAhECCQoEAwALBQIRBwoEDQYUAAQTBwULAAEODgESAwkb'
            'AQACEQIJCgQDAAI3EAIDCRIADgcBBA0GFAAIAgURAS8ACwcQFwgBMQELEQELAAQTBwULDQYU'
            'AAQTBwULAAEODgESAwkbAQACEQIJCgQDABEJAgoDBA0GFAAIAgURAQACJAEADwILAQAOBwUA'
            'FwIDAwgBDQYUAAQCFwEFAAMMAgMAEgIEAwQAGRIHEAURAQATDAEKABAEAQsNBhQAEwECFgcK'
            'ABMJAwwABQIoBwUxBAwCBRYAFwgCCwEEDQYUAAQTBwULABMFBxARDAMADgUHDwAPFQMMBQkI'
            'DQYUABsBBRUABAwCBRYAEgUBBBIBCgMAFwgCCwENBhQKAAIkAQATBQcQEQwDAA4FBw8ADxUD'
            'DAUJCA0GFAAEEwcFCwADDAIDAAsCChIBBAATCQMMAA4IAg8BDQYUCgACJAEAAwwCAwASAgQD'
            'BAAgCQIFAgATDAEKABAEAQsNBhQABBMHBQsAEQUJFhYBCwAXFQATCQoDAQUfBAASDAkICA0G'
            'FAAEEwcFCwADDAIDABICBAMEACIICQoYABMMAQoAEAQBCw0GFAAEEwcFCwABDg4BEgMJGwEA'
            'AhECCQoEAwAQCgsBAgsNBhQABA8CCAgAGAIDAgoCABAEAQsAFxUACgkKLgINBhkTBwULABIF'
            'Ag4DAQsADgUHDwACAAgBEQEKCwIFFQAPAQMCCA0GFAAIAREBCgsCBRUAGAIDAgoCABMJAwwH'
            'EAMAFgEBBQ0GFAAEEwcFCwAXBxAKCwADBwAJAwQAEwkBCAsBBR8EAB4cDQYUAAQTBwULAAED'
            'EgwBCwATCQMMABMHBQsEAAcOAAMMAQARBwsEDQYUAAQTBwULAAIIBAcAGAoHEwoAAgQAAwwB'
            'ACABDwcKFwgCCwENBhQABBMHBQsAAwwCAwASAgQDBAAeBwgVABMMAQoAEAQBCw0GFAAEAwIO'
            'DgADDAIDABICBAMEAB4BAggCBQIAEwwBCgAQBAELDQYUAAQDAg4OAAMMAgMAEgIEAwQAJggC'
            'BQEAEwwBCgAQBAELDQYUAAQTBwULABMJAwwAAgAEDAkPDwEFCQoRABcIAhIYABcIAgsBDQYU'
            'AAUCFgkBBQAFAQ4JCgELAA4HBQAXAgMDCAENBhQABBMHBQsAAwwCAwASAgQDBAAaBwoOEAQB'
            'ABMMAQoAEAQBCw0GFAAEEwcFCwADDAIDABICBAMEACABAgMMABMMAQoAEAQBCw0GFAoAEAoQ'
            'BBACCAAFAhYJAQUACQoOEAQBCwATCQMMAA8CEQkSDQYUCgACJAEAFwcCBAMJChEABBAWAQUX'
            'AAIDAwISGAAWBxMBBQ0GFAoAAiQBAAcKEgEAEwkBCAsBCwAXFQAbCRgJChEEDQYUCgACJAEA'
            'AwwCAwASAgQDBAAaEAUCEQIAEwwBCgAQBAELDQYUCgACJAEAAQ4OARIDCRsBAAIRAgkKBAMA'
            'EQkCCgMEDQYUABIMBRUEAgoDDAEPEA8AAgsHBQoEAAkDBAAEEgIXFwIFCw0GFAAEEwcFCwAT'
            'DAcEAQAKAg8BAAEPFwcLCQEEABcCAwMIAQ0GFAAEDwIICAAYAgMCCgIACwEECREKAQsADgcF'
            'AAECBBUAEAQBDQYUAAwCDw8BBQADDAIDAAQDBQkYAQQADAIFCw0GFAALAhERAQUAAwwCAwAS'
            'AgQDBAAsCQgIABMMAQoAEAQBCw0GFAAYCgkOAQATCQMMAAIAEQgBAg8JChEAEQcICwEKABcI'
            'AgsBDQYUABgKCQ4BAAMMAgMAEgIEAwQAGQkIAQoSAQATDAEKABAEAQsNBhQACwIREQEFABIF'
            'Ag4DAQsAAwcAFwEADgECAwwBBTEICREMAw0GFAAEAwIODgADDAIDABICBAMEACcJDgEAEwwB'
            'CgAQBAELDQYUAAQDEAULFQAEEwcFCwATCQMMAAIAEwkLAQAXCAILAQ0GFAAYCgkOAQADDAID'
            'AAEKDAIKEgEEAAIRCQgJAxUNBhQABAMCDg4AAwwCAwABCgwCChIBBAAJCgMBCAgJEQEKEgEN'
            'Bg=='),
        'entry_offsets': [284, 299, 315, 350, 365, 391, 421, 450, 480, 497, 529, 560, 595, 627, 661, 697, 736, 774, 797, 821, 861, 899, 937, 972, 1012, 1041, 1075, 1104, 1142, 1176, 1206, 1235, 1264, 1296, 1331, 1366, 1402, 1436, 1466, 1504, 1537, 1572, 1611, 1649, 1684, 1722, 1758, 1797, 1826, 1864, 1900, 1938, 1975, 2007, 2043, 2076, 2113, 2149, 2187, 2215, 2251, 2289, 2327, 2365, 2400, 2434, 2465],
    },
    'armor': {
        'count': 75,
        'first': 316,
        'payload': base64.b64decode(
            'PAEAAE8BAABvAQAAjgEAAK4BAADKAQAA5QEAAAkCAAAvAgAAVQIAAHcCAACXAgAAvAIAAOEC'
            'AAACAwAAHgMAAEEDAABkAwAAdAMAAJADAACvAwAAzgMAAPUDAAAbBAAANQQAAFkEAABxBAAA'
            'iAQAAJ4EAAC2BAAA2wQAAP0EAAAVBQAAPQUAAFQFAAB7BQAAiQUAAK0FAADKBQAA7AUAAAQG'
            'AAAnBgAASAYAAHEGAACXBgAAugYAAOAGAAADBwAAKwcAAFQHAAByBwAAmQcAAMEHAADoBwAA'
            'DwgAADUIAABZCAAAfggAAJsIAADACAAA6QgAABEJAAA5CQAAXgkAAIYJAACtCQAA1gkAAPEJ'
            'AAAWCgAAPQoAAFwKAACACgAApgoAAMgKAADmCgAAMAULCQoCBRUAEggHAwwJChENBhQFDwcF'
            'AA8CCwEABw4ADAIFCwEKAQsACAECAwwBBQ0GFAoAAgUPCAEDABIFAg4DAQsADgUHDwASBxYW'
            'AQUNBiECCQgABw4ACQoDAQUTBxsBCgASDAIJCgAICQoYBA0GFAoAAgUPCAEDAAcOABMHBRgB'
            'CwAECQgbAQUNBiECCQgAEgUCDgMBCwAOBQcPAA8VAwwFCQgNBhQFDwcFAA8CCwEABw4AAwwJ'
            'CggVAAwCDw8BBQELAAkFBwoNBhQABQcXAQADDAIDABICBAMEAC0KGwkECQUCABMMAQoAEAQB'
            'Cw0GFAAFBxcBAAMMAgMAEgIEAwQAIggJKCgCBQIAEwwBCgAQBAELDQYUCgACBQ8IAQMABwUK'
            'Ag8BCgMBCwATCQMMAAUQFwkBBA0GFAUPBwUAEgUCDgMBCwAOBQcPAAQDAQEIABYIAgMBDQYh'
            'AgkIAAkKDhAEAQsAEwkDDAADDAEAFgcTAQUABw4ADgkFAQ0GFAUPBwUACQoOEAQBCwATCQMM'
            'AAMMAQAWBxMBBQAHDgAJEgENBhQKAAIFDwgBAwACCwcFCgELABMJAwwACwkCDwcKCwQNBhQF'
            'DwcFABIFAg4DAQsADgUHDwALCQIPBwoLDQYhAgkIAA4CBAwJBwoBCwAOBQcPAAsFAhEHCgAE'
            'EgIIAQQNBhQABAwJAQgLAA8CCwEABw4ADAIFCwEKAQsACAECAwwBBQ0GFAAEDwIICAAEDAkB'
            'CAsNBhQABAwJAQgLABMFBxARDAMADgUHDwAJBQcKDQYUAAgCBREBABIIBwIYABMHBQoABxsB'
            'BQACBQ8HBQ0GFAAEDAkBCAsAEgUCDgMBCwAOBQcPAA8VAwwFCQgNBhQABAwJAQgLAAIICRsB'
            'ABMJAwwAAwwBABYHEwEFAAcOAA4JBQENBhQABAwJAQgLAAIICRsBABMJAwwAAwwBABYHEwEF'
            'AAcOAAkSAQ0GFAAEDAkBCAsADwILAQAHDgALCQIPBwoLDQYUAAQMCQEICwADDAIDABEQAgUL'
            'BAACEQIJCgQDAAQDBwoBDQYjCAcbAQQADwILAQAHDgAIAQIDDAEFDQYjCAcbAQQADwILAQAH'
            'DgAXBQcKKAENBiMIBxsBBAAPAgsBAAcOAAQDAQEIDQYjCAcbAQQADwILAQAHDgAPFQMMBQkI'
            'DQYjCAcbAQQAAwwCAwASAgQDACUMEAoLAgUCABMMAQoAEAQBCw0GIwgHGwEEAAMMAgMAEgIE'
            'AwAZAhcBBQATDAEKABAEAQsNBiMIBxsBBAAPAgsBAAcOAAsJAg8HCgsNBh0JChEAAwwCAwAR'
            'EAIFCwQAAhECCQoEAwAJCgQDAgoDAAsBAgMMDQYUABICFgAPAgsBAAcOAAgBAgMMAQUNBh0J'
            'FxcHCgADDAIDABMCBQsEAAcODgAEFgESCQIIAAIDAwISGAQNBhQABA8CCAgADAEIDw0GFAAM'
            'AQgPAAMMAgMAEgcbAQUEAAMMAQABCgMJBQEADAECCw0GFAAMAQgPABMFBxARDAMADgUHDwAP'
            'FQMMBQkIDQYUAAwBCA8AAwwCAwASAgQDBAAeAQIIABMMAQoAEAQBCw0GFAAMAQgPAA8CCwEA'
            'Bw4ACwkCDwcKCw0GIQIJCAAHDgASBRUEAwIILwASBQIOAwELAAgHChEAAhEHDQYUCgACBQ8I'
            'AQMAAwwCAwABCgwCChIBBAACEQkICQMVDQYnCREMAy8ACxAFAhcIAQAEEAkDAA4FBw8AAgAL'
            'CQQDAgoDAAgCCgsNBhQKAAcQAw4JAwAOAhsHBQELABcVAA8CBQMJAggAAgUDCQQDBA0GFAAE'
            'AgQMABMHGwEKABMJAwwAAgAQCgk3EAEAAwwFAQILDQYUAC4CEhgBAwADDAIDABYFBwMBEgME'
            'AAIRAgkKBAMADggCDwENBhQABQcXAQADDAIDAAEKDAIKEgEEAAkKAwEICAkRAQoSAQ0GFAAF'
            'BxcBAAkPFxABCwATCQMMAAMMAQAEFgkFCQMABw4ACAkRDAMNBhQABQcXAQAJCgQDCQgIAQsA'
            'EwkDDAADDAEAAQIFAwwfBAARBQISAQ0GFAAICREMAy8ACAcHBAExDgkDAwkKEQADEAoJEg0G'
            'HgECGxUAAgUPBwUAEgUCDgMBCwAJCgACAAsJBAMCCgMACAIKCw0GHgECGxUABAwJAQgLABIF'
            'Ag4DAQsACQoAAgALCQQDAgoDAAgCCgsNBhQABAwJAQgLAAcOABIFFQQDAggvABIFAg4DAQsA'
            'CAcKEQACEQcNBhkMCQEICwADDAIDABMCBQsEAAcODgAEAwIDEAQAAgkIDwEKAwQNBhQAEgIW'
            'AQACCAkbAQATCQMMAAMMAQAEFgkFCQMABw4AEwkKCw0GFAASCAcCGAABChIMAgoDAQsAEwkD'
            'DAABCBsBCgAPAhEJEg0GIwgHGwEEAAcOABIFFQQDAggvABIFAg4DAQsACAcKEQACEQcNBiMI'
            'BxsBBAADDAIDAAEKDAIKEgEAAhEJCAkDFQ0GFAAFCQoRAAcOABIFFQQDAggvABIFAg4DAQsA'
            'CAcKEQACEQcNBh0JChEADgIEDAkHCgELAAIOAwEFAAIKAAIKEQEIHwQADgECAwwBBQ0GHgEC'
            'GxUAEQgHGwEEABIFAg4DAQsACQoAAgALCQQDAgoDAAgCCgsNBhQADAECGxUADAEIDwASBQIO'
            'AwELAAkKAAIACwkEAwIKAwAIAgoLDQYUAAwBCA8ABw4AEgUVBAMCCC8AEgUCDgMBCwAIBwoR'
            'AAIRBw0GIggCEhgADAcHCwAXBQcQEQwDAA4FBw8AAgALCQQDAgoDAAgCCgsNBhQADAECCxcC'
            'CgsADgIbBwUBCwAXFQAPAgUDCQIIAAIFAwkEAwQNBhQACAkRDAMADwIEGAAPAgsBAAkKAAIA'
            'AwkRAQUfBAAICRgBCgEEBA0GFAAICREMAwASAhYAEwcbAQoABw4ABAkIGA0GFAASAhYAAwwC'
            'AwACEwIYAQoEAAgCAwEKAwACFwkICQMJAQQNBhQAAwUCCwkDCQcKAggADAIDABcFCQ8PCQoR'
            'ABMJAwwADwIRCRINBhQADAIDAA8CCwEABw4AAQoSDAIKAwELABIIBwMMDQYUAAQMCQEICwAH'
            'ChIBAAwBCAsAFxUAAgARBQECAwAMAQUHDQYhAgQYAAMMAgMACQQAAgADAQQDAg8BCgMAAwcA'
            'CwIFGAoBBAQNBhkQCQMABw4AAgUPBwUADwILAQAHDgAWEAUBAAQDAQEIDQYUABsBBAMAAwwC'
            'AwAPEAQDAQUEAAQDBQEKEQMMDQYUAAUHFwEACQ8PAQUEAQsACQoADAcIFQAWBxMBBQ0G'),
        'entry_offsets': [316, 335, 367, 398, 430, 458, 485, 521, 559, 597, 631, 663, 700, 737, 770, 798, 833, 868, 884, 912, 943, 974, 1013, 1051, 1077, 1113, 1137, 1160, 1182, 1206, 1243, 1277, 1301, 1341, 1364, 1403, 1417, 1453, 1482, 1516, 1540, 1575, 1608, 1649, 1687, 1722, 1760, 1795, 1835, 1876, 1906, 1945, 1985, 2024, 2063, 2101, 2137, 2174, 2203, 2240, 2281, 2321, 2361, 2398, 2438, 2477, 2518, 2545, 2582, 2621, 2652, 2688, 2726, 2760, 2790],
    },
    'items': {
        'count': 43,
        'first': 188,
        'payload': base64.b64decode(
            'vAAAAM4AAADcAAAA6QAAACMBAABkAQAAoQEAALQBAADJAQAA2wEAAO4BAAADAgAAIQIAAEkC'
            'AABiAgAAjgIAAJ4CAACtAgAA2QIAAO4CAAD+AgAACgMAABoDAAAoAwAAOAMAAEgDAABYAwAA'
            'aAMAAHUDAACIAwAAmwMAAK4DAADAAwAA1wMAAOkDAAD4AwAAEQQAACcEAAA9BAAAWAQAAHME'
            'AACOBAAAqgQAAB0BBAMHBQEEADI0AMKNHhwNBhoQBQEEABYHCQQHCg0GGhAFAQQABAMHCgEN'
            'BhwCBQMJAggIFQAFAQQDBwUBBAAWAgUDFR8EAB4cDWwaAgoABwoIFQAXAQAQBAELAAcQAwsH'
            'BwUEDQYcAgUDCQIICBUABQEEAwcFAQQAFgIFAxUfBAAeHAACCgsAIRwNbBoCCgAHCggVABcB'
            'ABAEAQsABxADCwcHBQQNBiYQCAgVAAUBBAMHBQEEABYCBQMVHwQAHhwAAgoLACEcDWwaAgoA'
            'BwoIFQAXAQAQBAELAAcQAwsHBwUEDQYdAQQDBwUBBAA2MjQAwo0eHA0GJhAICBUAwo0FAQQD'
            'BwUBBAAeHA0GHQEEAwcFAQQAMjQAwo0hHA0GHQEEAwcFAQQANjI0AMKNIRwNBiYQCAgVAMKN'
            'BQEEAwcFAQQAIRwNBiYQCAgVAMKNBQEEAwcFAQQAwo0eHAACCgsAIRwNBiYQCAgVAMKNBQEE'
            'AwcFAQQAwo0WAgUDFR8EAB4cAMKNAgoLACEcDQYdARsJGwEEAAcKAQDCjSwwHwsAAggIFQ0G'
            'GhAFAQQAwo0CCQgPAQoDBADCjQEkEgEWAwDCjQQDBwoBAAIKCwDCjSwwDQYaEAUBBAALAgUY'
            'CgEEBA0GGhAFAQQABAkIAQoSAQ0GJQUCCgQWBwUDBAAWAgUDFQAHEAMABw4ACxAKEQEHCgQA'
            'AgoLAAMHEwoEDQYZCAcTBAALBxMKAAIICAAOBwEEDQYaAgQDBAAiCAkoKAIFAg0GGgIEAwQA'
            'JgkFAg0GGgIEAwQAJQwQCgsCBQINBhoCBAMEACoQCBQICA0GGgIEAwQAKhAIIggCKAENBhoC'
            'BAMEACoQCCYFBwQDDQYaAgQDBAAqEAgZDAcSGA0GGgIEAwQAKhAIIAECAwwNBhoCBAMEAB4C'
            'BAMBDQYcAgUCCBUoAQQABwoBAA4HAQ0GHAEDBQkOCQEEAAcKAQAOBwENBh0CCQQBBADCjQQD'
            'BQEKEQMMDQYdAgkEAQQAwo0EAwIPCQoCDQYdAgkEAQQAwo0JCgMBCAgJEQEKEgENBh0CCQQB'
            'BADCjQIRCQgJAxUNBh0CCQQBBADCjQgQEhgNBh0CCQQBBADCjQ8CJAAeHAAXFQDCjTY0DQYd'
            'AgkEAQQAwo0PAiQAHhwAFxUAMg0GHQIJBAEEAMKNDwIkACEcABcVADINBiUBDxYHBQIFCQgV'
            'AAUCCQQBBAACAwMCEhgNBiUBDxYHBQIFCQgVAAUCCQQBBAAPAiQAHhwNBiUBDxYHBQIFCQgV'
            'AAUCCQQBBAAPAiQAIRwNBiUBDxYHBQIFCQgVAAUCCQQBBAALAQ4BCgQBDQYlAQ8WBwUCBQkI'
            'FQAFAgkEAQQAAhEJCAkDFQ0G'),
        'entry_offsets': [188, 206, 220, 233, 291, 356, 417, 436, 457, 475, 494, 515, 545, 585, 610, 654, 670, 685, 729, 750, 766, 778, 794, 808, 824, 840, 856, 872, 885, 904, 923, 942, 960, 983, 1001, 1016, 1041, 1063, 1085, 1112, 1139, 1166, 1194],
    },
}

# Magic NAME/DESC bank entries in spell name-index order (magic_text
# remap applies on shuffled seeds). Name entries: 2-byte school-icon
# prefix (c2 86 white / c2 87 black) + glyphs + TERM; desc entries:
# glyphs + TERM. Used to build the spell-tome extended item banks.
MAGIC_BANKS = {
    'names': {
        'payload': base64.b64decode(
            'woYaEAUBBsKGIAkCBsKGHAUHAwESAwbChiIICQoYBsKGIggJCgsKAgbChhkJCAEKEgEGwoYq'
            'EAgZDAcSGAbChi0KGwkEBsKGGhAFAgbChiAJAgUCBsKGKhAIIggCKAEGwoYeAQIIBsKGHAcJ'
            'BAcKAgbChiYBAgUGwoYqEAgmBQcEAwbChjMHJAbChhoQBQIRAgbChicJDgEGwoYgCQIRAgbC'
            'hh4BAggCBQIGwoYZAwcKAgbChikkCQMGwoYcBQcDAQUCBsKGLQobCQQJBQIGwoYaEAUCLgIG'
            'woYgCQIuAgbChioQCCABAgMMBsKGHgECCAIRAgbChiYQCAgxJwkOAQbChh4HCBUGwoYqEAgU'
            'CAgGwoYgCQQWAQgGwocmCQUBBsKHGQgBARYGwocmBxIQBAbChyUMEAoLAQUGwociCAkoKAIF'
            'CwbChyACBRgGwoclAQ8WAQUGwocZCAcTBsKHJgkFAgbChx4HCAsGwoclDBAKCwIFAgbChyYH'
            'EgIFAgbChxkIAQEWBQIGwoceAgQDAQbChxoHCg4QBAEGwociCAkoKAIFAgbChyYJBQIRAgbC'
            'hxkSBxAFEQEGwoclAQgBFgcFAwbChxkIBxMFAgbChyUMEAoLAhECBsKHIAECAwwGwodFEAIY'
            'AQbChxkDEAoGwociCAkoKAIRAgbChyIFAQIYBsKHGQIXAQUGwociCAkKCwbChyYIAgUBBsKH'
            'GQMHFgbChysCBRYGwocsCQgIBg=='),
        'entry_offsets': [0, 7, 13, 23, 31, 41, 51, 62, 70, 77, 85, 96, 103, 113, 120, 131, 137, 146, 153, 161, 171, 179, 186, 196, 207, 216, 224, 235, 245, 257, 264, 273, 282, 289, 297, 305, 315, 326, 333, 342, 349, 356, 363, 374, 383, 393, 401, 411, 422, 431, 441, 452, 461, 472, 480, 488, 495, 506, 514, 522, 530, 538, 545, 552],
    },
    'descs': {
        'payload': base64.b64decode(
            'HQEEAwcFAQQAwo0CAAgJAwMIAQAeHADCjQMHAAcKAQACCAgVDQYgAQIIBAALAg8CEQEAAwcA'
            'AggIABAKCwECCwAOBwEEDQYdAgkEAQQABwoBAAIICBUfBAALAQ4BCgQBDQYdAgkEAQQAEgIE'
            'AwEFHwQAARsCBAkHCg0GGhAFAQQACwIFGAoBBAQNBhwFARsBCgMEAAIICAAOBwEEAA4FBw8A'
            'EgIEAwkKEQAEFgEICAQNBh0BCxASAQQACAkRDAMKCQoRAAsCDwIRAQAXFQAMAggODQYdAgkE'
            'AQQABwoBAAIICBUfBAABGwIECQcKDQYdAQQDBwUBBAAeHADCjQMHAAcKAQACCAgVDQYgAQII'
            'BAALAg8CEQEAAwcAAggIABAKCwECCwAOBwEEDQYdAQsQEgEEAA4JBQEACwIPAhEBABcVAAwC'
            'CA4NBh0BBAMHBQEEAMKNAgAICQMDCAEAHhwAAwcAwo0BCgMJBQEAFgIFAxUNBhoQBQEEABYH'
            'CQQHCg0GIAUJGwEEAAIICAAOBwEEAAITAhUACQoAAwEFBQcFDQYdAQsQEgEEAAkSAQALAg8C'
            'EQEAFxUADAIIDg0GGhAFAQQABAkIAQoSAQ0GHQEEAwcFAQQAAgDCjQgHAwAHDgAeHAADBwDC'
            'jQcKAQACCAgVDQYdARsJGwEEAAcKAQDCjSwwHwsAAggIFQ0GIAECCAQACwIPAhEBAAMHAAII'
            'CAAQCgsBAgsADgcBBA0GHQEEAwcFAQQAHhwAwo0DBwABCgMJBQEAwo0WAgUDFQ0GGhAFAQQA'
            'BAMHCgENBiUFAgoEFgcFAwQAFgIFAxUABxADAAcOAAsQChEBBwoEDQYdAgkEAQQAFgIFAxUf'
            'BAALAQ4BCgQBDQYdAgkEAQQAFgIFAxUfBAABGwIECQcKDQYmEAgIFQDCjQUBBAMHBQEEAAcK'
            'AQDCjQIICBUfBAAeHA0GIAECCAQACwIPAhEBAAMHAAIICAAQCgsBAgsADgcBBA0GKQoMAgoS'
            'AQQAFgIFAxUfBAALAQ4BCgQBAAIRAgkKBAMACwECAwwNBh0BBAMHBQEEAMKNAgAIBwMABw4A'
            'HhwAwo0DBwABCgMJBQEAwo0WAgUDFQ0GHQEbCRsBBAAHCgEAwo0CCAgVAAIKCwAOEAgIFQDC'
            'jQUBBAMHBQEEAB4cDQYgAg8CEQEEAAIICAAOBwEEABMJAwwADAcIFQAICREMAw0GHQELEBIB'
            'BAALAg8CEQEADgUHDwAEFgEICAQAFxUADAIIDg0GKgERAgMBBAAHCgEADgcBHwQADwIRCRIC'
            'CAALAQ4BCgQBBA0GIAECCAQADgkFAQALAg8CEQEAAwcABwoBAA4HAQ0GHBADBAACCAgADgcB'
            'BAADBwAECAEBFg0GJwcTAQUEAAcKAQAOBwEfBAABGwIECQcKDQYgAQIIBAAICREMAwoJChEA'
            'CwIPAhEBAAMHAAcKAQAOBwENBiABAggEAAkSAQALAg8CEQEAAwcABwoBAA4HAQ0GIggJCgsE'
            'AAIICAAOBwEEABMJAwwACwIFGAoBBAQNBh0CCQQBBAAHCgEAAggIFR8EAAIDAwISGA0GHQEL'
            'EBIBBAACCAgADgcBBB8AChAPFwEFAAcOAAIDAwISGAQNBiABAggEAA4JBQEACwIPAhEBAAMH'
            'AAIICAAOBwEEDQYcAgUCCBUoAQQABwoBAA4HAQ0GIAECCAQACAkRDAMKCQoRAAsCDwIRAQAD'
            'BwACCAgADgcBBA0GJwcTAQUEAAEbAgQJBwoABw4AAggIAA4HAQQNBhwQAwQABwoBAA4HAQAD'
            'BwAECAEBFg0GIAcQFwgBBAAHCgEAAggIFR8EAAoQDxcBBQAHDgACAwMCEhgEDQYaAhAEAQQA'
            'DgcBBAADBwADEAUKAAcKAAECEgwABwMMAQUNBiABAggEAAkSAQALAg8CEQEAAwcAAggIAA4H'
            'AQQNBiABAggEAA4JBQEACwIPAhEBAAMHAAIICAAOBwEEDQYtCgQDAgoDCBUAGAkICAQAAggI'
            'AA4HAQQNBiUFAgoEFgcFAwQAFgIFAxUAAwcAFgUBGwkHEAQADggHBwUNBh0BCxASAQQABwoB'
            'AA4HAR8EAAoQDxcBBQAHDgACAwMCEhgEDQYgAQIIBAAICREMAwoJChEACwIPAhEBAAMHAAII'
            'CAAOBwEEDQYtCgQDAgoDCBUAGAkICAQABwoBAA4HAQ0GGgIICAQAAgoAAQIFAww3EAIYAQAD'
            'BwAEEwIICAcTAA4HAQQNBhwCBQIIFSgBBAAHCgEADgcBDQYgAQIIBAAJEgEACwIPAhEBAAMH'
            'AAIICAAOBwEEDQYcAQMFCQ4JAQQABwoBAA4HAQ0GHQIJBAEEABICBAMBBR8EAAIDAwISGAAC'
            'CgsAAhISEAUCEhUNBiIICQoLBAAHCgEADgcBABMJAwwACwIFGAoBBAQNBiIIAgQDBAACCAgA'
            'DgcBBAATCQMMAAgJEQwDAAIKCwAMAQIDDQYZAwcWBAADCQ8BAAIKCwAWAgUCCBUoAQQAAggI'
            'AA4HAQQNBiICCgkEDAEEAA4HAQQAAwcAAgoHAwwBBQALCQ8BCgQJBwoNBi0KBAMCCgMIFQAY'
            'CQgIBAAHCgEADgcBDQY='),
        'entry_offsets': [0, 38, 71, 98, 123, 139, 178, 212, 239, 266, 299, 328, 370, 384, 416, 444, 459, 497, 522, 555, 588, 601, 635, 659, 683, 717, 750, 790, 834, 878, 912, 948, 984, 1014, 1038, 1064, 1099, 1128, 1159, 1185, 1222, 1253, 1272, 1308, 1336, 1359, 1397, 1432, 1462, 1493, 1519, 1555, 1592, 1628, 1653, 1690, 1709, 1739, 1758, 1795, 1825, 1862, 1897, 1933],
    },
}

# Vanilla 0x10-byte TEXT headers of the items NAME/DESC banks (template
# for the rebuilt 108-entry banks; total-size field is patched in).
ITEMS_BANK_HDRS = {
    'name': b'\x00\x00\x00\x00TEXT\x01+\x00\x00\xf9\x02\x00\x00',
    'desc': b'\x00\x00\x00\x00TEXT\x01+\x00\x00\xc6\x04\x00\x00',
}
