"""open-progression runtime map-edit data — GENERATED by
re_only/gen_openworld.py. Do not hand-edit; regenerate instead.

Overworld (MAP_00) decompressed AMD grid = 255x255 u16 tile ids, stride 510, in a
heap arena re-decompressed on (some) overworld loads and relocating between boots.
Locate via ANCHOR = vanilla bytes of row 132 x155..174 (never edited/regressed):
grid_base = anchor_addr - ANCHOR_OFF. Tile attr table (512 x u16, movement
semantics, read live per step) located by its vanilla 512-byte prefix.

Two INDEPENDENT toggles select which edits the client applies (ApClient
_openworld_loop): EARLY_GRID_EDITS (early_open_progression) = Cornelia->Duergar foot
pass + Gulg/Crescent<->Ice canoe river; EXTENDED_GRID_EDITS (extended_open_progression)
= Duergar->Western Keep foot trail + Duergar<->Melmond canoe river. CANAL_ATT (canal
walk+sail shallows) is applied ALWAYS -- the canal is blown normally; we only make the
open canal walkable. See memories open-progression-rework, canal-shallows-plan.
"""

ANCHOR_OFF = 132 * 510 + 155 * 2          # 0x1082E
GRID_W, GRID_STRIDE = 255, 510

ANCHOR = bytes.fromhex("440070007100be00bf005400c100a300a400a5006a006b005100e600e700e600f600e70051004700")
ATT_PREFIX = bytes.fromhex("0ff00ff00ff00ff012f0020002000200020009f009f009f00ff00ff00ff00ff002f00ff002f002f002f002000200020002000200020002000ff00ff002000ff00ff000000ff002f002f00200020002000200020002000ff0020002000ff00ff002f00ff002f00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff002000200060006000600060012f012f012f006000600060006000000020002000ff00ff0060006000600060012f012f012f0060006000600060006000600060006000600060006000600060012f012f012f0060006000600060006000600060006000600060012f012f012f0030003000300030003000300030003000300030003000600060012f012f012f0030003000300030003000300030003000300030003000600060012f012f012f00300030003000300030012f012f012f012f012f012f012f012f012f012f012f00d000d000d000d00030012f012f012f012f012f012f012f012f012f012f012f00d000d000d000d00030012f012f012f012f012f012f012f012f012f012f012f00d000d000d000d000d0012f012f012f012f0060006000d00010012f012f012f013001300130000001300030003000300030009f009f009f009f003000300030003000d000d0006000600060006000e000e000e000e000e000e0003000300030003000d000d00060006000600060012f012f00100010001001300")

# {(x, y): tile_id} -- early_open_progression (Cornelia->Duergar pass + Gulg/Ice river)
EARLY_GRID_EDITS = {
    (116, 127): 50,
    (117, 127): 48,
    (119, 127): 49,
    (122, 127): 50,
    (123, 127): 39,
    (124, 127): 225,
    (118, 128): 400,
    (119, 128): 402,
    (120, 128): 45,
    (121, 128): 44,
    (122, 128): 240,
    (123, 128): 224,
    (117, 129): 435,
    (118, 129): 421,
    (119, 129): 404,
    (120, 129): 405,
    (121, 129): 402,
    (122, 129): 194,
    (123, 129): 166,
    (117, 130): 67,
    (118, 130): 68,
    (119, 130): 69,
    (120, 130): 200,
    (121, 130): 68,
    (122, 130): 209,
    (123, 130): 69,
    (119, 131): 84,
    (120, 131): 185,
    (211, 190): 398,
    (212, 190): 397,
    (210, 191): 11,
    (211, 191): 10,
    (212, 191): 496,
    (211, 192): 381,
    (212, 192): 378,
}

# {(x, y): tile_id} -- extended_open_progression (Duergar->WK trail + Melmond river)
EXTENDED_GRID_EDITS = {
    (76, 136): 49,
    (77, 136): 22,
    (78, 136): 179,
    (92, 136): 27,
    (93, 136): 25,
    (75, 137): 60,
    (76, 137): 456,
    (78, 137): 196,
    (79, 137): 165,
    (90, 137): 165,
    (91, 137): 37,
    (92, 137): 0,
    (93, 137): 0,
    (74, 138): 49,
    (75, 138): 76,
    (76, 138): 365,
    (77, 138): 196,
    (79, 138): 179,
    (88, 138): 199,
    (89, 138): 165,
    (90, 138): 165,
    (73, 139): 31,
    (74, 139): 240,
    (75, 139): 194,
    (76, 139): 464,
    (77, 139): 470,
    (79, 139): 179,
    (80, 139): 163,
    (88, 139): 199,
    (89, 139): 165,
    (75, 140): 383,
    (76, 140): 463,
    (77, 140): 455,
    (78, 140): 245,
    (79, 140): 244,
    (80, 140): 180,
    (81, 140): 180,
    (82, 140): 180,
    (84, 140): 196,
    (85, 140): 197,
    (75, 141): 383,
    (76, 141): 496,
    (77, 141): 380,
    (79, 141): 179,
    (81, 141): 180,
    (73, 142): 498,
    (74, 142): 498,
    (75, 142): 397,
    (76, 142): 496,
    (77, 142): 382,
    (78, 142): 85,
    (79, 142): 195,
    (80, 142): 197,
    (72, 143): 383,
    (73, 143): 11,
    (74, 143): 9,
    (75, 143): 496,
    (76, 143): 496,
    (77, 143): 382,
    (78, 143): 101,
    (79, 143): 61,
    (80, 143): 17,
    (70, 144): 83,
    (71, 144): 170,
    (72, 144): 383,
    (73, 144): 9,
    (74, 144): 378,
    (75, 144): 500,
    (76, 144): 500,
    (77, 144): 85,
    (78, 144): 225,
    (79, 144): 77,
    (70, 145): 202,
    (71, 145): 185,
    (72, 145): 383,
    (73, 145): 496,
    (74, 145): 382,
    (75, 145): 84,
    (76, 145): 100,
    (77, 145): 101,
    (78, 145): 24,
    (79, 145): 51,
    (71, 146): 99,
    (72, 146): 383,
    (73, 146): 496,
    (74, 146): 382,
    (75, 146): 189,
    (76, 146): 28,
    (77, 146): 55,
    (72, 147): 210,
    (73, 147): 472,
    (74, 147): 83,
    (75, 147): 85,
    (76, 147): 32,
    (72, 148): 165,
    (73, 148): 124,
    (74, 148): 99,
    (75, 148): 101,
    (76, 148): 51,
    (74, 149): 21,
    (75, 149): 53,
    (74, 150): 37,
    (94, 162): 225,
    (95, 162): 225,
    (94, 163): 494,
    (95, 163): 453,
    (96, 163): 11,
    (94, 164): 508,
    (95, 164): 225,
    (94, 165): 494,
}

# {(x, y): tile_id} -- northern_docks: two vanilla-template SHIP docks (south of
# Onrac @47-49,70; south of the Mirage desert @201-203,82). Dock tiles carry attr
# 0x0000 (walk + dock) in the UNTOUCHED attr table; the middle column is the berth.
NORTHERN_DOCKS_GRID_EDITS = {
    (47, 70): 279,
    (48, 70): 263,
    (49, 70): 263,
    (50, 70): 264,
    (201, 82): 279,
    (202, 82): 263,
    (203, 82): 263,
    (204, 82): 264,
}

# ---- terrain-CLASS map (encounter routing) ---------------------------------
# STATIC address (not the relocating tile arena): u16 W, u16 H, then W*H class
# bytes. class -> (rate_zone, terrain_type) via 0x08945810; terrain 0 = the zoned
# LAND table every vanilla canoe river uses. Carved river cells inherit the class
# of what they replaced (mountain/ocean/marsh) -> ocean-pool fights or rate_zone 6
# (rate 1..3 = never). The client rewrites these cells to RIVER_CLASS so encounters
# behave exactly like a vanilla river. Rebuilt by the game on overworld load, so
# the client re-applies alongside the grid edits (canary-checked).
TERRAINMAP_ADDR = 0x089B2884
TERRAINMAP_DATA_OFF = 4                   # past the u16 W, u16 H header
TERRAINMAP_W = TERRAINMAP_H = 255
RIVER_CLASS = 7                        # rate_zone 3, terrain 0 (zoned land)

# {(x, y): class} -- canoe cells of the early river (early_open_progression)
EARLY_RIVER_CLASS_EDITS = {
    (210, 191): 7,
    (211, 191): 7,
    (212, 191): 7,
}

# {(x, y): class} -- canoe cells of the Melmond river (extended_open_progression)
EXTENDED_RIVER_CLASS_EDITS = {
    (76, 138): 7,
    (76, 139): 7,
    (76, 140): 7,
    (76, 141): 7,
    (76, 142): 7,
    (73, 143): 7,
    (74, 143): 7,
    (75, 143): 7,
    (76, 143): 7,
    (73, 144): 7,
    (73, 145): 7,
    (73, 146): 7,
    (96, 163): 7,
}

# {tile_id: attr} -- canal cells become walk+sail shallows (0x000F); applied ALWAYS
CANAL_ATT = {372: 0x000F}

# {(x, y): tile_id} -- canal BRIDGE art: a 3-cell vertical bridge on column x=94
# (vanilla Cornelia-bridge tile ids, walk-only attrs already correct) replacing the
# shallows look of the open canal. GATED on the canal-open bit (CANAL_OPEN_ADDR/BIT):
# written only once Nerrick blows the canal, so the crossing is never drawn early.
# Foot connectivity is unchanged vs the shallows ford; x=93/95 stay ocean so the
# canal is still sailable.
CANAL_BRIDGE_GRID_EDITS = {
    (94, 156): 353,
    (94, 157): 369,
    (94, 158): 385,
}
# _SA = canonical save-block address; the live address is session-dependent, so the
# client MUST read it through self.sa() (the save block shifts, e.g. +0x7000). Read
# raw it is always 0x00 and the bridge is withheld forever (bug, 2026-07-29).
CANAL_OPEN_ADDR_SA = 0x08D1151D
CANAL_OPEN_BIT = 0x08
